version: '3.8'

services:
  postgres:
    container_name: finai_postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: finai_user
      POSTGRES_PASSWORD: finai_password
      POSTGRES_DB: finai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finai_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finai_user -d finai_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: finai_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finai.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - finai_network

volumes:
  postgres_data:
    name: finai_postgres_data

networks:
  finai_network:
    name: finai_network
    driver: bridge